AllCops:
  Exclude:
    - 'examples/*'

Metrics/LineLength:
  Max: 300

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 150

Metrics/ParameterLists:
  Max: 10

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/FileName:
  Enabled: false
