AllCops:
  Exclude:
    - 'examples/*'

Metrics/LineLength:
  Max: 300

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 150

Metrics/ParameterLists:
  Max: 10

Style/Encoding:
  EnforcedStyle: always
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always